color0 #554246
color1 #ffb4ab
color2 #ffb1c4
color3 #f5b5c4
color4 #ffb599
color5 #ffb1c4
color6 #f5b5c4
color7 #f0dee1
color8 #a28b8f
color9 #ffb4ab
color10 #ffb1c4
color11 #f5b5c4
color12 #ffb599
color13 #ffb1c4
color14 #f5b5c4
color15 #f0dee1

cursor                #f0dee1
cursor_text_color     #1a1113
background            #1a1113
foreground            #f0dee1
selection_foreground  #dac0c5
selection_background  #554246
active_border_color   #ffb1c4
inactive_border_color #554246
url_color             #ffb1c4

active_tab_foreground   #62082e
active_tab_background   #ffb1c4
inactive_tab_foreground #dac0c5
inactive_tab_background #554246
cursor_trail_color      #dac0c5
